version: '2'

services:
  server:
    env_file:
      - ./config/server.env
    build:
      context: ./server
    volumes:
      # Application path
      - ./server:/app
    ports:
      - "3000:3000"
    restart: always

  ui:
    env_file:
      - ./config/ui.env
    build:
      context: ./ui
    volumes:
      # Application path
      - ./ui:/app
    ports:
      - "8080:80"
      
    restart: always
